apiVersion: apps/v1
kind: Deployment
metadata:
  name: whois
spec:
  selector:
    matchLabels:
      run: whois
  replicas: 1
  template:
    metadata:
      labels:
        run: whois
    spec:
      containers:
      - name: whois
        image: lenvl/echo-server:v3
        ports:
        - containerPort: 1323
